[env]
_.python.venv = { path = ".venv", create = true }

[tools]
black = "latest"
ruff = "latest"
task = "latest"
uv = "latest"

[settings]
disable_backends = ["asdf", "pipx"]
pipx.uvx = true
python.uv_venv_auto = true
npm.bun = true
